# Server's port definition
server:
  port: 8019

# Spring configurations
spring:
  application:
    name: mcp-client-x

  # Spring AI configurations
  ai:

    # Azure OpenAI configurations
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-4o-mini
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        api-key: ${AZURE_OPENAI_API_KEY}

    # MCP Client to Server Connection Configuration
    mcp:
      client:
        enabled: true
        name: mcp-client-x
        version: 0.0.1
        initialized: true
        request-timeout: 20s
        root-change-notification: true
        type: async
        toolcallback.enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8018
              sse-endpoint: /api/v1/sse

# Logging configurations
logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE