server:
  port: 8014
spring:
  app:
    sain:
      documents:
        folder:
          location: /Users/gagandeepsingh/Workspace/AI Workspace/Copilot/Sandbox
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/?directConnection=true
      database: mongo-atlas-vector-ai-sandbox
  application:
    name: Spring AI Sandbox Notebook
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: codellama:13b
          temperature: 0.3
      embedding:
        options:
          model: mxbai-embed-large
    vectorstore:
      mongodb:
        initialize-schema: true
        collection-name: copilot-code-base
        index-name: codebase-index
